apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsecrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: infra@skymed.app.br
    privateKeySecretRef:
      name: letsecrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

